### ISSUE TITLE
Default group or rearranging of groups

### ISSUE THREAD

**Issue by sphh** [TheLastProject/Catima#101]
Would it be possible to either

* define a default group, which is focused, whenever the app is opened, or
* rearrange the groups, so that I can put the most used group (instead of `All`) in the first place.

Thanks.

**Comment by TheLastProject** [comment]
>define a default group, which is focused, whenever the app is opened

How about having the app remember what group was last focused and it automatically reopening that group next time you open the app? I think that may work too?

**Comment by sphh** [comment]
That's also an idea. If I were asked, I would opt for a configuration setting `Which group to open on start` with the options:

* `Remember last group`
* List of all available groups to select from …

This would keep everybody happy!

**Comment by TheLastProject** [comment]
The app will now remember the group chosen since 3c797b5ec9f3d31ec4d6ef66561540f177d00663.

I'll keep this open because your other requests aren't completely addressed, but if you feel this works better than expected feel free to close.

**Comment by sphh** [comment]
Great thank! That was really quick … I'll give it a try, when it arrives at F-Droid.

I pondered the different option and why I tend to prefer, that a fixed group is displayed when I start the app. I guess it has to do with the frequency you use the app. If you use it a couple of times every day, you will certainly recognize the position where you left it the last time. I use it maybe once a week, so I will not remember where I left. I will need something which I call an orientation phase. During this time I have to get my bearings and locate the group I am looking for: Is it left or right of the currently displayed group. If the app starts always at the same group, I know where to look. Mind you, that will only happen, when I close the app not being in my favourite group, which might happen rarely. But still … These are just my thoughts, I am still grateful that you took the LoyaltyCard app under your wings and that you are actively developing it!! Thanks! I am also looking forward to all those new amazing features, which I am sure, you have planned!

**Comment by TheLastProject** [comment]
Well, it may take a bit longer until it arrives on F-Droid. I want to use it for a few days to make sure I don't run into any stupid bug before I try to release it. But if you want I could build a .apk with that feature in it and post it here so you can already play with it.

I definitely see how a fixed starting group could be useful to you with that explanation yeah.

**Comment by sphh** [comment]
Since I don't use it that often (but then in a hurry!), don't worry with a quick release!

Thanks for seeing my point. Sometimes it is difficult to transport the user's view to the developers ;-)

**Comment by TheLastProject** [comment]
Okay I think this is what I want to do:

1. Make the All group visible in the groups list as an "Automatic group"
2. Add an Uncategorized automatic group showing all cards not in any group
3. Allow the user to disable All or Uncategorized (but not both because then cards not in any group wouldn't be visible)
4. Allow the user to mark a group as default group to start there on opening the app
5. Add some sorting thing by dragging groups up and down, removing the automatic alphabetic sorting and just adding a new group to the bottom always

Will be a fair bit of work so... step-by-step, and I may change the order. But I think this will make groups right about perfect.

**Comment by sphh** [comment]
Looks like I have opened a full can of worms (or groups)! That's far more than I suggested (especially the sorting and automatic and uncategorised groups). Wow!!

**Comment by evelikov-work** [comment]
Hey all, couple of ideas if I may:
 - instead of adding extra UI/code for groups, why don't we reuse tags?
 - wrt management, visibility, etc of groups(tags) - one can fillow the andOTP approach.
Namely: There's a (left) pull menu, with checkbox list of All/No, tag1, tag2, etc

**Comment by evelikov** [comment]
Hey all, couple of ideas if I may:
 - instead of adding extra UI/code for groups, why don't we reuse tags?
 - wrt management, visibility, etc of groups(tags) - one can fillow the andOTP approach.
Namely: There's a (left) pull menu, with checkbox list of All/No, tag1, tag2, etc

**Comment by TheLastProject** [comment]
What do you mean with reusing tags? I don't believe there is anything like tags in the codebase yet?

Moving the groups may be something to consider but for now the layout I designed seems to work okay.

**Comment by evelikov** [comment]
Looking at it closer: I must have been smoking something - there are no tags, only groups.
I would encourage you to look at andOTP's approach and UI, as it seems far more flexible and intuitive IMHO.

**Comment by TheLastProject** [comment]
Thinking of this more, adding more categories like ungrouped will just... complicated the codebase and the UI and I think I'll change #104 to actually be only manual group ordering.

If there are reasons to add more things in the future (like: "Favourites first", "Order alphabetically/last used", etc.") we will put them in a Drawer as @evelikov suggested. I think leaving the groups as they are is otherwise quite fine.
