### ISSUE TITLE
Support for NFC cards

### ISSUE THREAD

**Issue by IrgendwasmitBlech** [TheLastProject/Catima#166]
Thank a lot for this App. Maybe in the future it would be possible to add support for NFC cards?

**Comment by TheLastProject** [comment]
That would be nice, but I don't know how possible it is. NFC isn't something you just scan like a barcode, it's actually code of how it should respond to certain signals. I don't think any NFC card allows you to really export its code. I'll leave it open as enhancement, maybe someone else knows some way to make it possible, but I personally don't think it can be done.

**Comment by djechelon** [comment]
NFC cards are smart cards using asymmetric cryptography. There is just basically no way to _clone_ an NFC card, because cloning is what the request is looking for.

Please note that despite using NFC card for low-valuable stuff, all modern hardware kits are manufactured to be clone-proof. As a counter-example, consider modern transport passes are NFC for the very purpose of not being shared by different people.

**Comment by TheLastProject** [comment]
Yeah, that's what I thought. It's a shame for cases like these, but thanks for confirming, I'll close this one then because it is not reasonably possible.
