### ISSUE TITLE
Broken export of Cyrillic card names in csv

### ISSUE THREAD

**Issue by IllusiveMan196** [TheLastProject/Catima#197]
Export of card list containing Cyrillic card names results in something like this: РђР·СѓСЂ or ·ÑÑ or �������� if anything except Unicode UTF-8 is selected.
Examples are Windows-1251, ISO-8859-3 and UTF-7 (for fun) respectively.
Latin letters are fine in any of the encoding tables. As is this one is not an issue, as say LibreOffice or Excel (not sure about latter) allow to choose between encoding tables on file opening.

P.S. Table itself for some reason has 4 rows that look like redundant here (dirst rows, containing some number and _id) and after opening file one too many times in different encoding standards it is uneditable now...

P.P.S. Clicking on a "Privacy Policy" link in pop-up window sends me to said policy but does app deem it as accepted or no? (Said pop-up just self-closed and that's it)

**Comment by TheLastProject** [comment]
Could you please give me a Cyrillic card name that I could use in the app to test with?

>P.S. Table itself for some reason has 4 rows that look like redundant here (dirst rows, containing some number and _id)

There are no redundant rows, see https://github.com/TheLastProject/Catima/wiki/Export-format for the layout.

>P.P.S. Clicking on a "Privacy Policy" link in pop-up window sends me to said policy but does app deem it as accepted or no? (Said pop-up just self-closed and that's it)

The thing is, I don't collect any data. It makes no sense to be able to decline no data being collected whatsoever. The pop-up window is only there because of Huawei's insanity, who I decided to just give up on: https://twitter.com/SylvieLorxu/status/1379437902741012483. The next release won't have any such pop-up at all because, again, I don't collect any data and only Huawei insisted on this insanity.

**Comment by ErofeevK** [comment]
@IllusiveMan196, correct me if I'm wrong. The export proсess does not involve code page selection. And it looks like you select different code pages during importing to LibreOffice or Excel. If this is the case  than nothing even could be done with catima.  The encoding is text's property. So the csv will have the encoding that was used during export (utf8 in our case). The LibreOffice ask you about code page because this information is not the part of csv, and can only be guessed or asked from user. 
And UTF-8 is the best choice here since single CSV will allow  you to have cards  with different symbols otherwise incompatible. CP1251 will allow you to have cyrillic symbols  but no European diacritic  (ü ö ä ç å)  etc.   All that code pages are still here just because of compatibility,  we should  still deal with old documents and software.

**Comment by TheLastProject** [comment]
That's why I want to have a value to test to make sure that if I export and then open that export in Catima it goes fine. If people manually open and resave the file, then something else could be corrupting it and I can't do much about it.

I hope I get this info, otherwise I'll have to close this as missing info :(

**Comment by IllusiveMan196** [comment]
Yeah, the file with test-card is on the way

**Comment by TheLastProject** [comment]
After discussing this over email and testing, it turns out to not be broken after all. Closing as invalid.
