### ISSUE TITLE
Stocard import

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/Catima#223]
Stocard allows an export of your data because the GDPR requires it, even though it is made as cumbersome as they legally can, making you wait a full 30 days for no reason except because the GDPR allows them to take that long. Then, they deliver a passworded .zip file you can download.

- [x] Support zip files with passwords on import
- [ ] Import data

Having more Stocard exports than my own to test with would be helpful, feel free to email it to me (although I recommend removing `*/sync/data/users/*/devices/*/ip-location-wifi.*` from your export because damn that is creepy and I do not want to know this of contributors and/or users).

**Comment by Snuupy** [comment]
Assuming we have root on our android devices, are there any methods of importing the relevant appdata to Catima?

**Comment by TheLastProject** [comment]
I honestly do not know as I don't have any rooted devices myself. The waiting issue sadly is 100% political and not technical, Stocard has no technical reason to make you wait this long, they clearly just do it because they legally are allowed to take this many days.

I have no clue what kind of data you could get out of the Stocard app if your device is rooted, but I am willing to accept a patch for an "Advanced Import Options" option in Import Data which then lists options for data extracted on a rooted device or something ("Advanced Import Options" referring to: imports of data the average user has no way to reasonable retrieve themselves, in which I include rooting as it is definitely beyond the average user's capabilities).

Someone other than me will have to write (and maintain!) this code as I do not have any rooted devices myself.

**Comment by Snuupy** [comment]
I'm not sure if this is the best place to post this (or if you would prefer me to use github discussions), but I wanted to at least do a quick writeup in case anyone else was in the same spot as me:

I had the biggest problem trying to export my image data because I had a giftcard in image form stuck in the stocard app. I could take a screenshot of the image in the app but I considered that a "dirty" solution because I should be able to access the source files (it's ***my*** data!)

If you are rooted, the way to export images is as follows:

go to data/data/de.stocard/de.stocard.stocard/databases/sync_db, copy that to your computer, load the file in [DB Browser for SQLite](https://sqlitebrowser.org/dl/), filtering for your user ID. The images and entries will be available for export on the right side. I haven't dug far enough to find the membership numbers but the data is definitely all there.

I only have ~20 or so loyalty cards so for it's not worth it for me to automate but it can be done, they are just sqlite entries and I plan to manually move my data over.

I hope this was a bit insightful.

**Comment by TheLastProject** [comment]
They... store images inside the SQLite database? That... is an interesting design choice.

I think your message could work better in GitHub Discussions, maybe under "Show and Tell"? https://github.com/TheLastProject/Catima/discussions/categories/show-and-tell.

If you manage to anonymize your export more, we could maybe look into using it as a file to write an unit test with the expected result and then actually import the data directly.

And yeah, I get just 20 or so cards is not worth automating, but my fingers always start to itch for my keyboard when companies try to stop me from using my data :P
