### ISSUE TITLE
[Request] Use Keepass Database / Encrypted Storage

### ISSUE THREAD

**Issue by seniorm0ment** [TheLastProject/Catima#241]
I know there has been discussion about encrypting backups, however encrypted database would be very nice too. 

I had the idea though, could we not just utilize Keepass databases to withold the cards, and then just use Caitama as a frontend to display it nicely? There's not many fields.
Name can be username or title field, the card number can be in password, then notes could be notes.
Caitama would generate the barcode and display it how it currently does.

This would also increase compatibility greatly too, because the user can take the kpdb file and use it with any Keepass software if they wish to edit it elsewhere, change off caitama, what not. It would all be viewable as the fields would be in plaintext as exampled above. 

It also would come with the benefits of the solid encryption and functionalities of the kpdb and not needing to worry about Caitama handling that.
I think this would be really nice, and add universability, security, and functionality improvements to the app.

**Comment by TheLastProject** [comment]
I don't really see any benefits in this, honestly.

>encrypted database would be very nice too

Why? Android already ensures an app's internal storage is not readable by the user or any other apps (unless you have rooted your device and give an app root access). There is no security benefit to this.

>could we not just utilize Keepass databases to withold the cards

That would be a lot of work though, pretty much refactoring most of the codebase.

>This would also increase compatibility greatly too, because the user can take the kpdb file and use it with any Keepass software if they wish to edit it elsewhere, change off caitama, what not. It would all be viewable as the fields would be in plaintext as exampled above.

It's already exportable to a CSV, which has compatibility with way more software than just Keepass. So to me it seems this change would actually decrease compatibility.

>It also would come with the benefits of the solid encryption and functionalities of the kpdb and not needing to worry about Caitama handling that.

As I said, encrypted database has no use because Android's security model already prevents the data from being accessed. And making it compatible with the Keepass format would be WAY more work than the current simple SQL database structure: https://github.com/TheLastProject/Catima/blob/01bb4f0fc4a4e890f7f8fa6c29ec5311a199ef23/app/src/main/java/protect/card_locker/DBHelper.java

KeePass can already import from CSV files anyway: https://keepass.info/help/kb/imp_csv.html

An importer for a KeePass database into Catima, I don't know, maybe I could accept that if:
1. The amount of code is small
2. Someone who cares about using KeePass will maintain it (because I can only do so much work myself)

So, sorry, I'm closing this issue because I really do not see any benefit in it and only a lot of increased code complexity making the project harder to maintain.
