### ISSUE TITLE
Share bar/QR code as image

### ISSUE THREAD

**Issue by sphh** [TheLastProject/Catima#254]
Would it be possible to add a feature, so that it is possible to share the barcode / QR code as an image?

When I tried to share it, it is shared as an html page. If I want to transfer just the bar/qrcode, I have to make a screenshot and share that one …

**Comment by TheLastProject** [comment]
While I understand your request I kinda want to avoid the user having to ask themselves "does this person have Catima installed as well or not? Because if they do I should use option 1, otherwise I should use option 2".

I would think the best option would be if the webpage would also display the barcode (rendered in-browser with JavaScript to preserve privacy) with a way to save it as an image. That way people with Catima (or other apps that want to implement support for the shareable URLs) can easily import it while those without Catima can still save the barcode easily.

**Comment by sphh** [comment]
For me, it would be not a problem to distinguish between `Share as Catima card` and `Share as image`. IMHO this is quite clear.

I was surprised, that the browser opened after sharing. That was really unsuspected!

**Comment by TheLastProject** [comment]
I think https://github.com/TheLastProject/Catima-Website/pull/3 should fix it.

1. It is done completely client side, no card data sent to the server.
2. It promotes Catima because that is the experience I want the user to have
3. You can just share, you won't have to think at all if the other party has Catima installed or not.

**Comment by TheLastProject** [comment]
I consider this fixed in https://github.com/TheLastProject/Catima-Website/commit/3aee2dea1f0e24faef5724cee831221d1971b586.

**Comment by sphh** [comment]
IMHO you overcomplicate things and take a nanny approach to the user, believing s/he cannot distinguish between an image and a Catima card. Anyway, that is your decision.

If you cannot make a `Share as a QR code`, could you at least implement a way to save the QR code as image. That's all I want. Thanks.

**Comment by TheLastProject** [comment]
I understand I am not implementing this the way you like to see it, but experience has shown me that this nanny approach is sadly almost always necessary. It wouldn't be the first time an app gets a one star rating because an user doesn't understand what button does what they want no matter how "obvious" it is. So I am trying to make you happy while keeping the amount of choices as low as possible. This webpage thing allows me to make sharing possible to non-Catima users without having a Catima user share in a way where the receiving user can't one-click import it.

I will add an easy way to save the "card" on the webpage as image, so non-Android users on any platform can easily save shared cards locally. If you just want to save an image of the barcode for yourself, why not use Android's built in screenshot feature?

**Comment by sphh** [comment]
Because the screenshot deteriorates the quality of the bar/QR code: More often than not the borders are not sharp because of some scaling of the bar/QR code. In my view, in a QR code each tiny square (white or black) should be exactly one pixel. Then if you scale it to multiples of an integer number, the code will always stay sharp!

**Comment by TheLastProject** [comment]
The thing is, what you want (the high quality), is not really related to loyalty cards. It would only be interested for such a small amount of users that I won't implement that. It's just not worth the effort to code it in for something that for most users won't be interesting at all.

I looked around in F-Droid and https://github.com/dmitriy-ilchenko/QrAndBarcodeScanner seems to support saving to file and SVG. What you could do is:
1. Open your card in Catima
2. Make a screenshot with Android
3. Share the screenshot to "QR & Barcode Scanner"
4. Select Save Image there
5. Select SVG

So, sorry, but I won't implement that because there is another app that does what you want better.

The original request in your first question, "If I want to transfer just the bar/qrcode, I have to make a screenshot and share that one …" is solved by showing it in the webpage now.

**Comment by sphh** [comment]
Oh well … :disappointed:
