### ISSUE TITLE
String noGiftCards has non-corresponding glyph

### ISSUE THREAD

**Issue by StoyanDimitrov** [TheLastProject/Catima#276]
The string is a placeholder when there are still no cards. The export is now on its own menu item with different icon than the one used in the string `⋮`.

**Comment by TheLastProject** [comment]
Well, the import/export menu is on the top right which has such a menu:
![screenshot](https://raw.githubusercontent.com/TheLastProject/Catima/master/fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot-01.png)

Does this menu look different on your device? No 3 dots below each other? I thought it was always 3 dots, like, standardized in Android?

**Comment by StoyanDimitrov** [comment]
Not exactly. Probably because of the bumped up DPI.
![Screenshot_20210715-233236_Trebuchet](https://user-images.githubusercontent.com/10962709/125853828-fdf4da37-dc9b-4582-bbaa-796b35266faf.png)

**Comment by TheLastProject** [comment]
Hmm, I mean... they look like the same symbol to me?

![image](https://user-images.githubusercontent.com/1885159/125854657-d7111b62-9ff6-48ac-9334-c0fd5a78ac84.png)

So I don't really understand the issue well. Using this icon in the text was the idea of @comradekingu so maybe it helps more for you two to discuss this? I try to stay a bit away from all the exact texts to use everywhere as phrasing things isn't my strongest suit.

**Comment by StoyanDimitrov** [comment]
Just next to the dots are the two arrows pointing in opposite directions. AFAICT this is the Import/Export menu item.

**Comment by TheLastProject** [comment]
Oooooooooh. Wow, yeah. It is. I'm blind. Thanks for explaining.

It is indeed displayed there because it is set to show if enough room. But because importing and exporting is such a rare action (you will only import once, and export occasionally to make a backup, most likely not daily), I have just pushed 2e0482beef30469145cef1a4ae71c6346473f96b to always put it in that menu.

So the next release import/export will always be under the 3 dot menu and the string is now correct also on big screens.
