### ISSUE TITLE
String importCatimaMessage wrong case

### ISSUE THREAD

**Issue by StoyanDimitrov** [TheLastProject/Catima#277]
`catima.zip` mentioned in the string actually is `Catima.zip` exported from the app. Is it possible the casing of the export file changed between versions of the app?

**Comment by TheLastProject** [comment]
I have made the default filename all lowercase in e970bf185aa1e7385ed75bc769df4463de138782 just now. Feels weird to me for programs to create filenames with uppercases, even though it is just a small detail. So I think that fixes this issue: just use lowercase in the translations because it will be a lowercase .zip it creates next release.
