### ISSUE TITLE
String card_ids_copied not intended for translation

### ISSUE THREAD

**Issue by StoyanDimitrov** [TheLastProject/Catima#278]
The first argument of [`ClipData.newPlainText`](/TheLastProject/Catima/blob/ebca7ca150a4e4ba455dc682e7b78731045e727f/app/src/main/java/protect/card_locker/MainActivity.java#L92) is a label to developer and is not immediately visible to the user of the app.

**Comment by TheLastProject** [comment]
Well, Android's documentation describes it as [User-visible](https://developer.android.com/reference/android/content/ClipData) so it seems to me it seems best to expect this string to be shown to the user in some case?

**Comment by StoyanDimitrov** [comment]
User-visible indeed, but with a [twist](https://stackoverflow.com/questions/33207809/what-exactly-is-label-parameter-in-clipdata-in-android).

**Comment by TheLastProject** [comment]
Well, it doesn't seem like there is any real reason to remove this string? It's not causing any trouble and it is documented as "user-facing" so... who knows, maybe some other app will one day show it and then we're prepared? I think I'll just leave it in, honestly, because it's already there and translated in many languages and it can't hurt, at most help in the future.

Thanks for all your suggestions though, I really appreciate the look at all the small details!

**Comment by StoyanDimitrov** [comment]
One reason is to free the future translators from taking the time to go over this string.

**Comment by TheLastProject** [comment]
Oh, I definitely agree that I should try to limit the amount of work translators have and I am glad you have helped me already to do so. I am just not really convinced that the work saved is worth it because it is already translated in several languages and the Android documentation does imply this could be shown to the user at some point. If I delete it now and we find out that later it is shown it would be more work.

As I understand it, another app could actually use this to help display things. For example, if I understand the Android code correctly, a clipboard manager could save some space by showing the "Copied card IDs" text by default to make it fit in a single line more easily.

**Comment by StoyanDimitrov** [comment]
I wont insist because really is not a big deal. And the wasted time already outweighs the benefit, if any.

Thank you for all the kind words and for the time and work you put into this useful app.
