### ISSUE TITLE
Use only encrypted backup

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/Catima#290]
Android's backup framework allows us to state we only want encrypted backups. We should opt-in for that: https://developer.android.com/guide/topics/data/autobackup#define-device-conditions

**Comment by TheLastProject** [comment]
I just noticed that https://github.com/tasks/tasks supports enabling/disabling cloud backups in settings. That would be even better if someone can find out how that is done

**Comment by djechelon** [comment]
Trying to take a look @ this in the weekend

Assignee: @djechelon

**Comment by TheLastProject** [comment]
Assigned you :)

**Comment by djechelon** [comment]
Wt<strike>f</strike> heck?

https://github.com/Zighinetto/Catima/runs/3324946895?check_suite_focus=true

**Comment by TheLastProject** [comment]
Oh yeah, this happens sometimes. No clue why. If you re-run the tests they will complete normally :laughing:

**Comment by djechelon** [comment]
> I just noticed that https://github.com/tasks/tasks supports enabling/disabling cloud backups in settings. That would be even better if someone can find out how that is done

How? My theory is the following

Android backups are managed by Manifest. True of false, I couldn't see if there is a way to programmatically switch, nor I am interested. The OS reads the manifest to tell whether the backup should be done or not. If so, then the work is done by the Backup Agent

[Long story short](https://github.com/tasks/tasks/blob/ece69999572caa68ca00b0b10ec44a50178eb3dc/app/src/main/java/org/tasks/backup/TasksFileBackupHelper.kt#L37) (gimme teh codez) you would want to create a `SharedPreference` object controlling backup yes/no choice. As you can see in the referenced code, they just `return` when the app preference is off.

**About Android Backup**

It is normally done by brutally copying files from the app's storage dir. Applications such as Tasks.org _apparently_ make a JSON dump. Which makes things interesting too as with regards to forward-compatibility of backups

**Issues with Catima**

>If you've upgraded your development devices to Android 9, you need to disable and then re-enable data backup after upgrading. This is because Android only encrypts backups with a client-side secret after informing users in Settings or the Setup Wizard.

I am having a hard time understanding this. Does it mean that if we deploy a version of Catima with client side cryptography to production devices it will not migrate the old backups to use crypto, breaking them completely? Or does it suggest that you can simply run a new emulator with Android 9+ from scratch and have encrypted backups to test?

What we really want is a seamless upgrade experience.

**My original idea**

Since Catima is made for older SDKs, the change is simple as editing the manifest and adding an XML backup rules file, one for default SDK and one, SDK27, with directive to require `clientSideEncryption`. This has the desired effect of being backwards-compatible. And is the simple-most implementation, without taking testing into account yet.

Done for today

**Comment by TheLastProject** [comment]
Oh, I only just noticed this part:

```
clientSideEncryption: The user's backup is encrypted with a client-side secret. This form of encryption is enabled on devices running Android 9 or higher as long as the user has enabled backup in Android 9 or higher and has set a screen lock (PIN, pattern, or password) for their device.
```

I know not everyone uses a screen lock, especially those are the kind of users who do not have the skills to make manual exports...

I guess that leaves making backups an option as the only good option for those privacy-conscious who don't want to back this app up to Google (if they don't use Lineage + Seedvault) but... wouldn't those privacy-conscious people just disable Google backup completely?

I am starting to think trying to change anything here will just make the situation worse for everyone involved instead of better...

**Comment by djechelon** [comment]
Yyyyyyup!

Catima is typical app for people who collect a lot of loyalty cards. While it works with eu dgc, does not mean it is a safety critical app.

If user employs a pin, backups are all encrypted. There is not that of confidential info in Catima worth effort of protection over comfort of use.

Having the option of disabling backups is a good go, instead.
Opt out

**Comment by TheLastProject** [comment]
Yeah, I guess we could try to implement the thing Tasks uses at some point for those who, for some reason, want to generally enable backups but disable it for Catima. But honestly, this is such an unlikely case and introduces another thing that can go wrong to the point that I'm not sure it's worth it to even try.

So I am going to close this as "wontfix" because backups are encrypted if you use a code and the privacy-conscious who don't want Catima backed up probably have all Android app backups disabled. And I am not quite sure if it's worth to create an issue to add an opt-out feature just because of how difficult it is to get this backup stuff right...
