### ISSUE TITLE
Weblate ignores some string formatting, may be worth looking at it.

### ISSUE THREAD

**Issue by IllusiveMan196** [TheLastProject/Catima#301]
So the string is this
Delete these <xliff:g xmlns:xliff="urn:oasis:names:tc:xliff:document:1.2">%d</xliff:g> cards permanently?

Weblate straight up ignores formatting in the middle in translation for some reason, otherwise safe to merge.

**Comment by TheLastProject** [comment]
Sorry, I don't really understand what you mean. Could you maybe add a picture to this issue to help me understand?

**Comment by TheLastProject** [comment]
Ah, you're referring to https://hosted.weblate.org/translate/catima/catima/uk/?checksum=cbbd76008e0082cb.

Looks like Weblate doesn't really understand the situation of the original string having no format string in singular but having one in plural. It's just a warning, so no real issue, but we should report this one to Weblate. I'll do that after work.

**Comment by TheLastProject** [comment]
Actually, Weblate is right. Because the "One" version, in Android, actually refers to more than only the number 1:
![image](https://user-images.githubusercontent.com/1885159/127711533-0492cdb0-b608-4468-b0f8-fe5c38809f05.png)

I've updated the source string in f4f3f2e3077dcb1b739df0baf4315dcb99643636 to work around this plurality weirdness in Android.
