### ISSUE TITLE
Add permanent  lock screen Notification

### ISSUE THREAD

**Issue by Mannshoch** [TheLastProject/Catima#326]
I tried it with Catima and changed back to printed barcode that I sticket onto my wallet.

Please add a possibility to stick a notification  with the barcode to the lockscreen for a faster access.

**Comment by TheLastProject** [comment]
I don't really understand you well, could you please explain what you want in a bit more detail, preferably with a picture or something to make it extra clear?

**Comment by Mannshoch** [comment]
I thought about a fast way to open my shopping barcodes.
May you could permanently add a Catima notification per barcode on the lockscreen. So I'm able to take my Phone and instead of unlock it and search the Catima app from the home screen, drag the notification and Open the correct barcode directly. That way I could use the home screen for others and have fast access from lockscreen.

**Comment by TheLastProject** [comment]
That sounds like a very non-standard way to implement it that probably almost nobody will want except maybe you.

Because every feature takes time to write and, even more importantly, to maintain so it doesn't randomly break, I think it would be good to go for a more standard way.

Some of my suggestions here:
1) Maybe you just want #226 to be able to quickly open Catima from the lock-screen?
2) Alternatively, if you have a recent-enough Android feature, you could long-press the Catima icon to quickly go to your most recent cards. That way you would only need one entry for Catima on your home screen.
3) You could use an app like [QuickTiles](https://f-droid.org/en/packages/com.asdoi.quicktiles/) to create a Quick Settings Tile to open Catima from the quick tiles, accessible from a quick pull-down on the lock screen.

Are there specific reasons any of these options aren't good enough? Please also note that as long as you don't disable "Prevent lock screen" in settings you could open the card before going to the store and turn off your screen, at which point that card shows up the moment you turn on your screen again.

**Comment by Mannshoch** [comment]
Quicktiles seems nice. I wil try it that way. I have to many apps on my Phone so I do not wish to have Catima there. That Way I could get Catima from where I needed. Catima is the only App I need to get from my pocket to the desk with the correct app open as short as possible.

**Comment by TheLastProject** [comment]
I'll close this now under the assumption QuickTiles is a viable workaround for you and https://github.com/TheLastProject/Catima/issues/146 may help in the future.
