### ISSUE TITLE
syncing with another phone - export/import using QR code idea.

### ISSUE THREAD

**Issue by mathieujobin** [TheLastProject/Catima#343]
Hi,

thanks for your app, works very well. 
I want to use it on my 2nd phone and copy all my cards over to my other phone.
The export method saves a file somewhere on my phone.
I must then find and send to myself by email, download on my other phone for import.

That's a lot of steps and requires an external service.
What if Catima would be generating a large QR code containing the entire collection. Maybe there is a limit, but I think it would be sufficiently large for most users. Could be split into multiple QR code for multi-step import.

On my second phone, I would scan the QR from the first phone to import the cards.

Thank you.

**Comment by TheLastProject** [comment]
This is a complex feature, not sure if it is worth the effort. It seems better to me to figure out some standardized syncing method

**Comment by TheLastProject** [comment]
Thanks for the suggestion, but I'll close this issue, because I don't really see the benefit in it, especially not given how complex this would be to implement.

Given Catima already has a "Send..." option after creating an export, simply sharing it to an application such as [Share via HTTP](https://f-droid.org/en/packages/com.MarcosDiez.shareviahttp/) (which can generate a scannable QR code) will work over local WiFi. Otherwise other apps can be used.

I am not interested in this feature because I do not feel the trade-off between the added code (and thus continued maintenance costs) versus the usefulness for most users is really worth it.
