### ISSUE TITLE
Privacy issue when sharing a code?

### ISSUE THREAD

**Issue by Altonss** [TheLastProject/Catima#369]
Hello,

I just noticed, that when sharing a code/card from Catima with somebody else, a url containing the data is generated. This could lead to serious privacy issues, because the website is seeing all the data unencrypted when we open the url...
Most of the time this isn't really an issue as these are often just loyalty cards, but very private information could also be shared. The user using the share feature could be unaware of the privacy issue.

Thanks for the great app :)

**Comment by TheLastProject** [comment]
Well, yes, but also no! Let me explain how the sharing system Catima uses protects your privacy :)

The old system had some privacy issues, which is why I changed the format in Catima 2.0: https://github.com/TheLastProject/Catima/wiki/Card-sharing-URL-format#catima-20.

The new format uses the URL's [hash](https://developer.mozilla.org/en-US/docs/Web/API/URL/hash) property. The great thing about this property is that it is never sent to the server you're connecting to.

So, let's take the following card as an example: https://catima.app/share#store%3DRestaurant%26note%3DNote%2Babout%2Brestaurant%2Bhere%26balance%3D0%26cardid%3D98765432%26barcodetype%3DCODE_128%26headercolor%3D-10902850

When you open this in a browser instead of Catima, only the part before the `#` symbol gets sent to the server (you can verify this in your browser console).

So, the server only knows you requested https://catima.app/share.

On this share page is some JavaScript that will run locally in your browser to show you a preview of the card: https://github.com/TheLastProject/Catima-Website/blob/master/_pages/share.md (you'll have to click "Raw" because otherwise the code isn't readable).

So, when you share a card with someone, even if they open it in their browser, the server will never know the actual data. The card preview is generated in your browser itself.

The only problem with this approach is that you have to trust me to not put evil code in the share JavaScript to send your card to me anyway, but well, if I wanted to be evil why would I wait until you press share ;)

So yeah, I hope this helps you to understand how I designed the system in a way so that the server will never see your loyalty card info when you share it, even when someone opens it in their browser :)

**Comment by Altonss** [comment]
Thanks a lot for your very detailed explanation! So the only weakness would be malicious Javascript. 

> but well, if I wanted to be evil why would I wait until you press share ;)

That's not really the same with the android app, as the source code is directly compiled by F-Droid (if you download if this way). 
Moreover the permissions of the app limit malicious behaviors: Catima hasn't network access as far I am aware.

**Comment by TheLastProject** [comment]
Well, true, but F-Droid doesn't check every single line of code either. I could probably hide something evil if I wanted to. But yeah, Catima doesn't have network access indeed.

Malicious Javascript is indeed the only issue, if I find a way to lower that risk I'll definitely see about implementing it :)

**Comment by Altonss** [comment]
Thank you very much for your reply ;) The potential issue is not so big, but yes if someone finds a way to improve safety that would be great to implement :)
