### ISSUE TITLE
Catima should warn before sharing cards

### ISSUE THREAD

**Issue by cannycartographer** [TheLastProject/Catima#564]
Hi,
I recently shared a card using Catima but didn't realise before sharing it that Catima would create a webpage (un-password protected) for that card. This is a potentially major privacy issue, particularly for sensitive logins / card details.

To avoid this Catima should warn users when they try to share, that sharing will create a URL for the card (rather than e.g. sending a JPG directly via Whatsapp).

Secondly, and related to this, it doesn't seem to provide any way to unshare cards, or automatic expiry dates for cards. Expiry dates could be set automatically at 30/90 days (or users could be asked), and should be applied retrospectively to previously shared cards.

Many thanks for all the development work.

**Comment by TheLastProject** [comment]
Actually, that URL **is** the card. So it is no different from sharing an image directly: https://github.com/TheLastProject/Catima/issues/369#issuecomment-912813635. The reason it is an URL instead of a weird file is to make sharing easier over different platforms that may block binary files and have a fallback when an user does not have Catima installed.

For revoking a card you accidentally shared with the wrong person, well, that's the same as when you shared a photo of your card: only the company you have the loyalty card from can do that. It is impossible for me to implement an expiry date without reducing the privacy provided by the current solution, and I am not willing to make that trade-off (I like not being able to see any card data).

**Comment by LeSpocky** [comment]
The URL generated is something like https://catima.app/share#store%3Dexample%26note%3D%26balance%3D0%26cardid%3D1234567%26barcodetype%3DEAN_8%26headercolor%3D-5414233 for example. There's a real webserver behind that, answering those requests. No one can guarantee all the accesses to that won't be logged, stored, or analyzed one way or another. At least the server operator can do, without any user noticing. This is not privacy by design.
