### ISSUE TITLE
Blurry text on the preview icon

### ISSUE THREAD

**Issue by Altonss** [TheLastProject/Catima#628]
Here a screenshot of the "preview icon" of an element. The letter on the colour background is blurry and pixelated. Would there be a way to improve the scaling here?
Android 5.0.1
Samsung Galaxy Core Prime

![image](https://user-images.githubusercontent.com/66519591/143878290-20f53f50-9e1a-4667-9aa4-8ff992dfb507.png)

**Comment by TheLastProject** [comment]
I think I know what's going wrong here, I just never noticed it on my own device. I'll fix it.

**Comment by Altonss** [comment]
> I think I know what's going wrong here, I just never noticed it on my own device. I'll fix it.

It would interest me to know all this works and what is causing the issue, so I can progress and maybe contribute in the future. So if you could just mention the commit that is correcting the issue, this would be great. Thanks in advance <3

**Comment by TheLastProject** [comment]
Okay, this is a bit more work than I expected.

The issue is that in the `Utils` class there is a `generateIcon` function.

This always generated a "letter icon" of 46dp, because the image used to always be the same size kinda. However, this value is now a bit too low.

The proper fix would take into consideration what size it needs to be generated for and base it on that. However, getting the size of an entry on the main screen before rendering is pretty complex.

So, instead, I went for the naive fix and just doubled the generated letter image resolution by changing the values used in the code in 9cd2f66b40fc16e464b67ee8e482e5458c67efef.

Sure, it's not really the perfect fix, but it should do for now :)

**Comment by Altonss** [comment]
Thanks a lot for the explanation :) I look forward to seeing what the next version will be like.

**Comment by TheLastProject** [comment]
Well, given you were thinking of maybe contributing in the future, building the app yourself in Android Studio would be a good start. You can install it next to the normal installation, the default ("debug") target of Catima has its own name and package ID so you won't have to uninstall your normal install. That way you can see it early :)

**Comment by Altonss** [comment]
I don't feel really confortable installing Android Studio, as the flatpak is marked as proprietary so I am not really. But if I find some time I will maybe find another way of building it xD

**Comment by TheLastProject** [comment]
Ah, yeah... the source code status of Android's tooling is... confusing to say the least: https://wiki.debian.org/AndroidTools

It should theoretically be possible to edit and build Android apps in a 100% libre environment, but it is so complex that I personally gave up on trying and can't really help there.
