### ISSUE TITLE
Card view overlaps with system top notification bar

### ISSUE THREAD

**Issue by Altonss** [TheLastProject/Catima#634]
As in the following image, we see that in card view the content overlaps with the top notification bar:
![image](https://user-images.githubusercontent.com/66519591/143933881-7029e9f3-50b7-40fe-bfaa-6d3c0d9f200f.png)

Is it an intended behavior? Personnaly I don't think this is a very good behavior (for example when you have pictures as an icon).
I already think to have a fix for that, I would just need to do a PR :)

**Comment by TheLastProject** [comment]
It is intended because it looks better. On images we darken the part below the top bar, to prevent unclarity.

In fact, Google design guidelines (https://material.io/components/app-bars-top) state: "Bars can contain imagery. Prominent top app bars are recommended for image use because they provide more space."

So, this is actually the correct way to do it as per Android guidelines.

**Comment by Altonss** [comment]
Oh that's fine I didn't know. 

> On images we darken the part below the top bar, to prevent unclarity.

I noticed when selection a white color or something very light, we cannot see the top notification bar anymore, as in:
![image](https://user-images.githubusercontent.com/66519591/143935240-4ae30b92-f1fa-4b7b-8bcf-bc9e59bf08e4.png)

**Comment by TheLastProject** [comment]
Oh that IS a bug!
