### ISSUE TITLE
Feature request (bug): when modifying the number of a card, display warning if the number format not supported

### ISSUE THREAD

**Issue by Altonss** [TheLastProject/Catima#662]

**Comment by TheLastProject** [comment]
It's not triggered until you go to the barcode view, yeah. Easiest fix for this would be some relayout work.

**Comment by Altonss** [comment]
The easiest fix would just to run the verification function also just in the edit menu while modifying the ID, and not only in the barcode view :)

**Comment by TheLastProject** [comment]
Fair, but I wanted to make some layout changes anyway :)

**Comment by Altonss** [comment]
Ah all right then, I didn't know about that. What are these layout changes about?

**Comment by TheLastProject** [comment]
Fixed in a7a775bc014f7201f7608bb10a343620268f7428 by putting everything related to the barcode together.

![image](https://user-images.githubusercontent.com/1885159/147888939-77500a93-294f-4686-935b-4a82c19b4ea4.png)
![image](https://user-images.githubusercontent.com/1885159/147888944-3244dde9-3ae8-4ff3-aa72-3e5be04a992c.png)
